db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "file"
  sslmod: "disable"
  password: "password0701"

admin:
  id: "1"
  name: "Allayar"
  email: "abcd.gmail.com"
  password: "1234567"